matrix:
  include:
    - os: osx
      osx_image: xcode7.1 # Yosemite
    - os: osx
      osx_image: xcode7.3 # El Capitan

before_install:
  - brew update

install:
  - brew install ansible --HEAD

before_script:
  - export PATH="$HOME/.pyenv/bin:$PATH"

script:
  - ansible-playbook -i localhost playbook.yml --tags "test" -v
