os: osx

before_install:
  - brew update

install:
  - brew install ansible --HEAD

before_script:
  - export PATH="$HOME/.pyenv/bin:$PATH"

script:
  - ansible-playbook -i localhost playbook.yml --tags "test" -v

notifications:
  email: false
