---

- name: create ghq directory
  file: path={{ dotfiles }} state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: clone dotfiles repository
  git: repo={{ repository }} dest={{ dotfiles }}

- name: install (clone) oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/Users/{{ ansible_user_id }}/.oh-my-zsh

- name: create oh-my-zsh custom theme
  file: path=/Users/{{ ansible_user_id }}/.oh-my-zsh/custom/themes state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: create ~/.config/nvim/dein directory for nvim
  file: path=/Users/{{ ansible_user_id }}/.config/nvim/dein state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: get dein.vim
  shell: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh

- name: install dein.vim
  shell: sh ./installer.sh /Users/{{ ansible_user_id }}/.config/nvim/dein

- name: create links
  file: src={{ item.src }} dest={{ item.dest }} state=link force=true
  with_items: '{{ links }}'
  ignore_errors: true

- name: add path of zsh to /etc/shells
  lineinfile: dest=/etc/shells line=/usr/local/bin/zsh state=present owner=root group=wheel mode=0644
  become: yes

- name: change shell to zsh
  shell: chsh -s /usr/local/bin/zsh
  become: no
  ignore_errors: True

- name: write profile of iterm2
  command: defaults write com.googlecode.iterm2 PrefsCustomFolder -string '{{ dotfiles }}/iterm2'
