---

- name: create ghq directory
  file: path={{ dotfiles }} state=directory owner={{ ansible_user_id }} group=staff mode=0755

- name: clone dotfiles repository
  git: repo={{ repository }} dest={{ dotfiles }}

- name: make install dotfiles
  command: make install chdir={{ dotfiles }}

- name: change shell to zsh
  shell: chsh -s /bin/zsh
  become: no
  ignore_errors: True

- name: write profile of iterm2
  command: defaults write com.googlecode.iterm2 PrefsCustomFolder -string '{{ dotfiles }}/assets/iterm2'

- name: install atom packages
  command: apm install --packages-file "$HOME"/.atom/packages.list
