---

- name: install pyenv
  homebrew: name=pyenv state=latest

- name: find latest python version
  shell: 'pyenv install --list | grep -E "^\s+3\.9\.\d+$" | tail -1'
  register: python_version

- name: install python
  shell: "pyenv install {{ python_version.stdout }}"

- name: rehash pyenv
  shell: "pyenv rehash"

- name: set default python
  shell: "pyenv global {{ python_version.stdout }}"

- name: update pip itself
  shell: "pip install --upgrade pip"

- name: install packages for vim
  shell: "pip install pynvim flake8 --ignore-installed"
