---

- name: brew tap
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{homebrew_taps}}'

- name: brew update
  homebrew: update_homebrew=yes

- name: brew install packages
  homebrew: >
    name={{ item.name }}
    state=latest
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: '{{homebrew_packages}}'

- name: brew-cask install packages
  homebrew_cask: name={{ item.name }} state=present
  with_items: '{{homebrew_cask_packages}}'
