homebrew_taps:
  - caskroom/cask
  - homebrew/core
  - homebrew/dupes
  - homebrew/python
  - homebrew/science
  - homebrew/versions
  - homebrew/x11
  - neovim/neovim
  - nikolausdemmel/devel
  - oame/nlp
  - osrf/simulation
  - staticfloat/julia

homebrew_packages:
  - { name: glpk }
  - { name: open-mpi }
  - { name: freeimage }
  - { name: collada-dom }
  - { name: mogenerator }
  - { name: lz4 }
  - { name: tmux }
  - { name: vim, install_options: [with-lua] }
  - { name: spidermonkey }
  - { name: octave }
  - { name: suite-sparse421 }
  - { name: libiconv }
  - { name: cminpack }
  - { name: wget }
  - { name: veclibfort }
  - { name: hugo }
  - { name: libvo-aacenc }
  - { name: apple-gcc42 }
  - { name: cowsay }
  - { name: jbig2dec }
  - { name: git }
  - { name: nkf }
  - { name: qrupdate }
  - { name: poco }
  - { name: transfig }
  - { name: lapack }
  - { name: xpdf }
  - { name: sdl_ttf }
  - { name: sdl_image }
  - { name: pyenv-virtualenv }
  - { name: leiningen }
  - { name: fontforge }
  - { name: heroku }
  - { name: opencv }
  - { name: direnv }
  - { name: lesstif }
  - { name: neovim }
  - { name: rbenv }
  - { name: portmidi }
  - { name: suite-sparse }
  - { name: node }
  - { name: boost-python }
  - { name: libzzip }
  - { name: sbt }
  - { name: arpack }
  - { name: mongodb }
  - { name: swig }
  - { name: coreutils }
  - { name: jq }
  - { name: gawk }
  - { name: julia }
  - { name: nmap }
  - { name: libltc }
  - { name: libusb }
  - { name: gnutls }
  - { name: cloog }
  - { name: libgcrypt }
  - { name: python3 }
  - { name: peco }
  - { name: ghq }
  - { name: metis }
  - { name: libtar }
  - { name: libyaml }
  - { name: rlwrap }
  - { name: qhull }
  - { name: flann }
  - { name: hdf5 }
  - { name: tree }
  - { name: valgrind }
  - { name: openmotif }
  - { name: reattach-to-user-namespace }
  - { name: argp-standalone }
  - { name: bison }
  - { name: gnupg }
  - { name: sdl_mixer }
  - { name: sbcl }
  - { name: ossp-uuid }
  - { name: gsl }
  - { name: zsh }

homebrew_cask_packages:
  - { name: alfred }
  - { name: appcleaner }
  - { name: atom }
  - { name: bettertouchtool }
  - { name: totalspaces }
  - { name: caffeine }
  - { name: dropbox }
  - { name: google-chrome }
  - { name: google-japanese-ime }
  - { name: gyazo }
  - { name: insomniax }
  - { name: iterm2 }
  - { name: itsycal }
  - { name: latexit }
  - { name: magican }
  - { name: mendeley-desktop }
  - { name: monolingual }
  - { name: seashore }
  - { name: skitch }
  - { name: skype }
  - { name: slack }
  - { name: the-unarchiver }
  - { name: trim-enabler }
